### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by imaginetheheadline** [christoller/tic-tac-toe#1]
# Project 1

Really great work, Chris. Your final project looks very much like your wireframe. I love all the extra touches, like the way the cat points to whose turn it is. The animations are great. Adds just that little bit of polish. Nice job on the different screens for setting the names and starting the game.

## HTML

Looks really good.

```html
<img src="" alt="Pointing Cat" id="cat-ref">
```

Lol, excellent.

Nice use of classes and id's.

## CSS

Good work here, too. I like that you have different sections for everything. I would say that you could improve on removing some duplication. Perhaps you could make more use of element selectors to style all elements like buttons a certain way, or use more classes to style elements similarly. Another idea you can try is the concept of "utility classes". Then you could add common styling to some elements.

For instance, instead of

```html
<button id="end-game-button"></button>
```

```css
#end-game-button {
    margin: 5% 0;
    border: 3px solid black;
    border-radius: 15px;
    background-color: rgb(255, 255, 255);
    transition: 0.3s;
    font-family: 'Patrick Hand',
    cursive;
    font-size: 1em;
    padding: 10px 15px;
}
```

Maybe your element is more like:

```html
<button id="end-game-button" class="white-button rounded transition cursive"></button>
```
```css
button {
    margin: 5% 0;
    border: 3px solid black;
    font-size: 1em;
    padding: 10px 15px;
}
.white-button {
    background-color: rgb(255, 255, 255);
}
.rounded {
    border-radius: 15px;
}
.transition {
    transition: 0.3s;
}
.cursive {
    font-family: 'Patrick Hand', cursive;
}
```

This could help you remove some duplication and make your styling more re-usable. Rather than providing all of how a particular element should look like to that element selector, you can compose its style by applying generic classes that you could easily apply to any other similar element.

You could in this way condense your css dramatically. :)

### Setup

```css
:root {
    font-size: 1.2em;
}

* {
    box-sizing: border-box;
}
```

Nice!

### Repeat player page styling

You have some good uses of classes and id's but I feel this was one place where you might have missed an opportunity. It looks like you could have added the class of `player-display` for example to your `#player-one-display` and `#player-two-display` elements, cause the styling for these looks virtually identical.

### absolute and fixed position

Nice job on these too.

## JavaScript

Very nice. Looks very straight-forward and well-organised. Nice use of functions, and setting up all your variables and event listeners first. This make it easy to follow what your code is doing. `initializeGame` is on point.

Nice code for preventing both to have the same avatar. I like that your gameBoard and winningConditions are stored in code.

Preventing pointer events is cool too.

### Resetting board

Minor thing, you probably don't need to do this:

```js
if (box.hasChildNodes()) {
    box.removeChild(box.firstElementChild);
}
```

You can use `box.innerHTML = ''`
